### ISSUE TITLE
Invalid ParameterGroup takes 45 minutes to roll back

### ISSUE THREAD

**Issue by pplu** [aws-cloudformation/aws-cloudformation-resource-providers-rds#124]
Hi,

   I just wanted to make you aware of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1014, which seems to affect this resource provider. I am re-reporting this here, since there has been no interaction (maybe I was reporting to the wrong repo).

**Comment by osdrv** [comment]
The corresponding issue in the CFN roadmap repo was resolved. Closing this one as well.
