### ISSUE TITLE
[DBCluster] add 60s delay after the first modify call in update handler

### ISSUE THREAD

**Issue by ammokhov** [aws-cloudformation/aws-cloudformation-resource-providers-rds#13]
need to add 60s propagation delay to avoid `InvalidDBClusterStateFault` exception

**Comment by osdrv** [comment]
We have root-caused this issue to an eager flow control release by DBClusterParameterGroup: whenever there is a modification on DBClusterParameterGroup, it finishes the stabilization way too early. As an alternative to sleep(60) we are using probing: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/master/aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java#L334-L337. This proved to be sufficient to get this issue addressed. Closing for now.
