### ISSUE TITLE
[DBCluster] ignores DBSubnetGroupName property when creating a clone

### ISSUE THREAD

**Issue by ammokhov** [aws-cloudformation/aws-cloudformation-resource-providers-rds#15]
this issue is an internal tracker of this [issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/336) until resource is published

**Comment by mikey-** [comment]
@ammokhov I recently commented on the linked issue to say that while looking into it, I was poking around the aws-cloudformation-resource-providers-rds repository and something stood out to me:

>... I wonder if this issue occurs due to the fact that `dbSubnetGroupName(model.getDBSubnetGroupName())` is not included in one of the [RDS resource provider's translator function](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/256a0ce59d44a6f09c5380401a5ad33bf0eef15e/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java):
> https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/256a0ce59d44a6f09c5380401a5ad33bf0eef15e/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java#L61-L68

What do you think?

**Comment by ammokhov** [comment]
> @ammokhov I [recently commented on the linked issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/336#issuecomment-824364731) to say that while looking into it, I was poking around the aws-cloudformation-resource-providers-rds repository and something stood out to me:
> 
> > ... I wonder if this issue occurs due to the fact that `dbSubnetGroupName(model.getDBSubnetGroupName())` is not included in one of the [RDS resource provider's translator function](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/256a0ce59d44a6f09c5380401a5ad33bf0eef15e/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java):
> > https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/256a0ce59d44a6f09c5380401a5ad33bf0eef15e/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java#L61-L68
> 
> What do you think?

this is right. we should include the field. I think @osdrv is the primary engineer and will be able to address

**Comment by mikey-** [comment]
Thank you @ammokhov! Thank you @osdrv!

**Comment by chucksellick** [comment]
Please, this fix would be much appreciated, I just wasted most of a day trying to resolve why I was getting this error:

```
Subnet group <DBSubnetGroupName> is different from subnet group of cluster <DBClusterIdentifier>
```

Presumably this is because the cluster subnet group name is silently changing to default, therefore it now conflicts with the instance I was also creating which *does* have the correct subnet group name.

Well I guess for now I just clone the DB by hand until these options work.
