### ISSUE TITLE
DBCluster creation failing with "Tag keys cannot start with the reserved prefix "aws:""

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/aws-cloudformation-resource-providers-rds#239]
When attempting to deploy a simple [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html) resource the stack creation fails with the following error

> Resource handler returned message: "Tag keys cannot start with the reserved prefix "aws:".

Even more curiously, this seems to only be happening in the ap-northeast-1 region, but not eu-west-1. (will update case as issue is detected in other regions). When deploying an RDS Cluster resource to *ap-northeast-1*, the error is observed. However, when deploying to *eu-west-1* creates just fine.

Curiously, it seems that the two regions are running different schemas of this particular resource type as well. let's spare the verbose details for now, but comparing the output of the following commands will reveal significantly different schemas.

``` aws cloudformation describe-type --type-name AWS::RDS::DBCluster --type RESOURCE --region eu-west-1```
``` aws cloudformation describe-type --type-name AWS::RDS::DBCluster --type RESOURCE --region ap-northeast-1```

Replication
---

Deploying this template to the *ap-northeast-1* region will fail at creation with the above-mentioned error

```
Parameters:
  MasterUserPassword:
    Type: String
    NoEcho: true
    Default: 'password123'
  MasterUsername:
    Type: String
    Default: MyName123
  DatabaseName:
    Type: String
    Default: testdb

Resources:
  MyDbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: !Ref DatabaseName
      Engine: postgres
      EngineVersion: "13.4"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: 100
      DBClusterInstanceClass: "db.m5d.large"
      StorageType: "io1"
      Iops: 3000
    DeletionPolicy: Delete
  MyDbInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref MyDbCluster
      DBInstanceClass: "db.m5d.large"
      Engine: postgres
      EngineVersion: "13.4"

```

The following [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) event can be seen.

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "XXXXXXXXXXX",
        "arn": "arn:aws:iam::00000000000:user/yooser",
        "accountId": "00000000000",
        "accessKeyId": "XXXXXXXXXXXXXXXXXXXXX",
        "userName": "yooser",
        "sessionContext": {
            "sessionIssuer": {},
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2022-07-22T12:15:18Z",
                "mfaAuthenticated": "false"
            }
        },
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2022-07-22T12:15:26Z",
    "eventSource": "rds.amazonaws.com",
    "eventName": "CreateDBCluster",
    "awsRegion": "ap-northeast-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "InvalidParameterValueException",
    "errorMessage": "Tag keys cannot start with the reserved prefix \"aws:\".",
    "requestParameters": {
        "databaseName": "testdb",
        "engineVersion": "13.4",
        "allocatedStorage": 100,
        "backupRetentionPeriod": 1,
        "dBClusterIdentifier": "sandbox-mydbcluster-klxxxxxx4txqs",
        "engine": "postgres",
        "masterUserPassword": "****",
        "dBClusterInstanceClass": "db.m5d.large",
        "tags": [
            {
                "value": "sandbox",
                "key": "aws:cloudformation:stack-name"
            },
            {
                "value": "arn:aws:cloudformation:ap-northeast-1:00000000000:stack/sandbox/ef377e50-09b7-11ed-b47a-xxxxxxxxxx",
                "key": "aws:cloudformation:stack-id"
            },
            {
                "value": "MyDbCluster",
                "key": "aws:cloudformation:logical-id"
            }
        ],
        "port": 3306,
        "storageType": "io1",
        "masterUsername": "MyName123",
        "iops": 3000
    },
    "responseElements": null,
    "requestID": "xxxxxx-xxxx-xxx-xxxxx-xxxxxxxx",
    "eventID": "xxxxxx-xxxx-xxx-xxxxx-xxxxxxxx",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "00000000000",
    "eventCategory": "Management"
}

```

Conclusion
---
It seems that the Cloudformation service is not expecting the service-managed tags with aws-reserved prefixes. Would you kindly help determining if a bugfix is required here, and if possible, offer potential workarounds in the meantime.

Please let me know if further information is required and I will be happy to provide.

**Comment by osdrv** [comment]
Thank you very much for the report. The information is sufficient.

**Comment by osdrv** [comment]
The issue appeared to be concerning the RDS API and to my best knowledge is now completely fixed. @greg5123334 any chance you could confirm DBCluster creation works as expected now?

**Comment by osdrv** [comment]
Please reopen the issue if a similar symptom occurs.
