### ISSUE TITLE
[DBCluster]Validation of required property for DBCluster with GlobalClusterIdentifier

### ISSUE THREAD

**Issue by yueqwang** [aws-cloudformation/aws-cloudformation-resource-providers-rds#24]
1. need to change the properties restriction in template.
    1. if GlobalClusterIdentifier exist,
        1. check if global cluster has members
        2. if global cluster has members, cannot specify username and password
    2. action needed: because we cannot check if global cluster has members from template, allow either to have or don’t have user name and password if globalClusterIdentifier exists

**Comment by osdrv** [comment]
We got rid of these schema-based validations as there is no way we can customize the error message. This case is propagated to the RDS API. Closing for now.
