### ISSUE TITLE
[DBCluster]Update delete handler for DBCluster for case with GlobalClusterIdentifier

### ISSUE THREAD

**Issue by yueqwang** [aws-cloudformation/aws-cloudformation-resource-providers-rds#25]
When we delete dbcluster that is member of global cluster, we need to remove it from global cluster first:
https://www.google.com/search?client=firefox-b-e&q=remove-from-global-cluster   
action needed:    
1. first check if globalClusterIdentifier != null, if yes, trigger removeFromGlobalCluster first
2. current removeFromGlobalCluster only accept arn, need to do use describeDBCluster to get the cluster arn and pass the arn to removeFromGlobalCluster

**Comment by osdrv** [comment]
This was completed in the current DeleteHandler version: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/master/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/DeleteHandler.java#L54-L56. Closing for now.
