### ISSUE TITLE
Include DbClusterResourceId as accessible attribute of DbCluster

### ISSUE THREAD

**Issue by ghost** [aws-cloudformation/aws-cloudformation-resource-providers-rds#43]
(This issue duplicates https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/192, as I'm interpreting the contribution guidelines in this way; if that is incorrect, please let me know.)

This attribute is needed for some specific circumstances, and cannot currently be retrieved through GetAttr.

**Comment by osdrv** [comment]
This attribute was added to the resource and rolled out in all AWS regions. Closing this issue for now.
