### ISSUE TITLE
How can I use these repositories in my yaml templates?

### ISSUE THREAD

**Issue by MrAliMohsin** [aws-cloudformation/aws-cloudformation-resource-providers-rds#468]
Apologies if this is a very dumb question, and I don't know where else to ask, but I am very new to Cloudformation. Moreover, I am not easygoing with GitHub as well. I was looking for rds instance automated backup replication and in [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html) I was unable to find the property "AutomaticBackupReplicationRegion".
In this repository, very recently the property "AutomaticBackupReplicationRegion" [is added ](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/tree/master/aws-rds-dbinstance#automaticbackupreplicationregion). However I am not sure how to use this repository as I just create the yaml templates using aws syntax and when I added this property in my AWS::RDS::DBInstance resource, it is throwing error. 
![image](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/assets/12434732/ba61ca93-30f0-419f-bf07-1b88b7b79ae5)

**Comment by khebul** [comment]
Hello, when the property will be publicly available, we will update the public documentation with the new property. As of now, even if the commit which has added this property has been merged, the feature is not yet deployed. When ready, we intend to add this property to the public documentation and include the example json and yaml templates.
