### ISSUE TITLE
Is the `Engine` property optional for the `AWS::RDS::DBCluster` resource?

### ISSUE THREAD

**Issue by nikpivkin** [aws-cloudformation/aws-cloudformation-resource-providers-rds#494]
The [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-engine) says that the `Engine` property is optional. Then what is the default value and why is the engine parameter required in [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html) and [terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#engine)?

**Comment by dbbh** [comment]
When restoring your DBCluster or creating a ReadReplica, the Engine will be inherited from the source DBCluster.
